name: Automatique Matchs Sync

on:
  workflow_dispatch:
  schedule:
    # S'exécute à chaque heure, de 6h à 23h (minuit)
    - cron: '0 6-23 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code du dépôt
        uses: actions/checkout@v4

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install node-fetch

      - name: Lancer le script de mise à jour
        env:
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        run: node scripts/update.js
