name: Automatique Matchs Sync

on:
  schedule:
    - cron: '0 0 * * *' # Exécution automatique tous les jours à 00:00 UTC
  workflow_dispatch:     # Permet le déclenchement manuel

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installation des dépendances
        run: npm install firebase-admin node-fetch@2

      - name: Exécution de la synchronisation
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: node sync.js
